name: Update MSVC toolchain on Windows
description: Update Visual C++ build tools on Windows

runs:
  using: composite

  steps:
    - run: |
        dotnet tool update -g dotnet-vs;
        vs update all;
      shell: pwsh
